<script lang="ts">
  import type { FederationChild, NormalizedCorpus, OkfNode, OkfRelationship } from '$lib/types';
  import { okfConceptPresentation, trustTierLabel } from '$lib/okfV02';
  import { renderSafeMarkdown, smallNodeLinks, smallNodeMetadataRows } from '$lib/viewer/smallNodePresentation';
  import { relationshipPresentation } from '$lib/viewer/relationshipPresentation';
  import InspectorSections from './InspectorSections.svelte';
  let { detailNode, smallCorpus, detailRelationships, sourceUrl, selectedFederationChild, outsideScope = false, inspectNode, inspectRelationship, loadFederationChild }:
    { detailNode: OkfNode; smallCorpus: NormalizedCorpus | null; detailRelationships: OkfRelationship[]; sourceUrl: string;
      selectedFederationChild?: FederationChild; outsideScope?: boolean; inspectNode: (id: string) => void; inspectRelationship: (relationship: OkfRelationship) => void; loadFederationChild: (child: FederationChild) => void } = $props();
  let okf = $derived(okfConceptPresentation(detailNode));
  const jsonText = (value: unknown) => JSON.stringify(value, null, 2);
  const metadataDisplayValue = (value: unknown) => value === undefined || value === null || value === '' ? 'Not specified (metadata gap)' : typeof value === 'object' ? JSON.stringify(value) : String(value);
</script>

{#if outsideScope}<p class="scope-context" role="status">This record is outside the current result scope. Its details remain open for reference.</p>{/if}
          <span class="badge">{detailNode.type || 'Node'}</span>
          {#if smallCorpus?.okfVersion}<span class="badge">OKF {smallCorpus.okfVersion}</span>{/if}
          <span class="badge" data-trust-tier={okf.trustTier}>{trustTierLabel(okf.trustTier)}</span>
          <span class="badge" data-lifecycle-status={okf.status}>{okf.status}</span>
          {#if okf.stale}<span class="badge warning" data-stale="true">Stale</span>{/if}
          <h2>{detailNode.title}</h2>
          <p>{detailNode.description || detailNode.summary || detailNode.source || detailNode.id}</p>
          {#if selectedFederationChild && (selectedFederationChild.descriptor || selectedFederationChild.discovery.routes.some((route) => route.purpose === 'descriptor' || (!route.purpose && ['published', 'raw'].includes(route.kind))))}
            <div class="detail-actions">
              <button type="button" onclick={() => loadFederationChild(selectedFederationChild)}>Load child bundle</button>
            </div>
          {/if}
<InspectorSections>
  {#snippet overview()}
          {#if detailNode.body}
            <section class="markdown-body" aria-label="Markdown body">
              {@html renderSafeMarkdown(detailNode.body, sourceUrl)}
            </section>
          {/if}
          <h3>Relationships</h3>
          {#if !detailRelationships.length}<p>No relationships supplied for this record.</p>{/if}
          {#each detailRelationships.slice(0, 20) as relationship}
            {@const outgoing = relationship.source === detailNode.id}
            {@const neighbour = outgoing ? relationship.target : relationship.source}
            {@const presentation = relationshipPresentation(relationship)}
            <div class="record-relationship">
              <span>{outgoing ? 'Outgoing' : 'Incoming'} · {outgoing ? relationship.kind || 'related' : presentation.inverseLabel || relationship.kind || 'related'}</span>
              <strong>{smallCorpus?.nodes[relationship.source]?.title || relationship.source} → {smallCorpus?.nodes[relationship.target]?.title || relationship.target}</strong>
              <div><button type="button" onclick={() => inspectRelationship(relationship)}>Inspect relationship</button><button type="button" onclick={() => inspectNode(neighbour)}>Inspect {smallCorpus?.nodes[neighbour]?.title || neighbour}</button></div>
            </div>
          {/each}
          {#if detailRelationships.length > 20}<p>Showing 20 of {detailRelationships.length} relationships. Use Links to browse the current scope.</p>{/if}
  {/snippet}
  {#snippet evidence()}
          <section class="okf-v02-summary" aria-label="OKF trust, lifecycle and provenance">
            <h3>Trust, lifecycle and provenance</h3>
            <p class="muted">OKF v0.2 signals are advisory context for deciding whether and how to use this concept.</p>
            <dl>
              <dt>Trust tier</dt><dd>{trustTierLabel(okf.trustTier)}</dd>
              <dt>Lifecycle</dt><dd>{okf.status}{detailNode.status ? '' : ' (default)'}</dd>
              <dt>Generated by</dt><dd>{okf.generated.by || 'Not declared'}</dd>
              <dt>Generated at</dt>
              <dd>
                {okf.generated.at || 'Not declared'}
                {#if okf.generated.basis === 'legacy-v0.1-timestamp'}<small>Legacy OKF v0.1 timestamp fallback</small>{/if}
              </dd>
              {#if okf.verified.length}
                <dt>Verified</dt>
                <dd>{okf.verified.map((event) => `${event.by || 'Unknown actor'}${event.at ? ` · ${event.at}` : ''}`).join('; ')}</dd>
              {/if}
              {#if okf.staleAfter}
                <dt>Stale after</dt><dd>{okf.staleAfter}{okf.stale ? ' · stale now' : ' · currently fresh'}</dd>
              {/if}
              {#if okf.usageWindow}
                <dt>Usage window</dt><dd>{okf.usageWindow.from || '…'} → {okf.usageWindow.to || '…'}</dd>
              {/if}
            </dl>
            {#if okf.sources.length}
              <h4>Provenance sources</h4>
              <div class="okf-source-list">
                {#each okf.sources as provenanceSource, index}
                  <article>
                    <strong>{provenanceSource.title || provenanceSource.id || `Source ${index + 1}`}</strong>
                    <code>{provenanceSource.resource}</code>
                    {#if provenanceSource.author}<span>Author {provenanceSource.author}</span>{/if}
                    {#if provenanceSource.last_modified}<span>Modified {provenanceSource.last_modified}</span>{/if}
                    {#if typeof provenanceSource.usage_count === 'number'}<span>Usage {provenanceSource.usage_count.toLocaleString()}</span>{/if}
                    {#if provenanceSource.legacy}<small>Legacy # Citations fallback</small>{/if}
                  </article>
                {/each}
              </div>
            {/if}
          </section>
          {#if okf.attestedComputation}
            <section class="attestation-contract" aria-label="Attested Computation contract">
              <h3>Attested Computation contract</h3>
              <p><strong>Declared contract only.</strong> Explorer does not execute the computation, executor or attester when a bundle is opened.</p>
              <dl>
                <dt>Runtime</dt><dd>{okf.attestedComputation.runtime || 'Not declared'}</dd>
                <dt>Computation</dt><dd>{okf.attestedComputation.computation || (okf.attestedComputation.inlineComputation ? 'Inline fenced computation' : 'Not declared')}</dd>
                <dt>Parameters</dt><dd>{okf.attestedComputation.parameters.length ? okf.attestedComputation.parameters.map((parameter) => `${parameter.name}: ${parameter.type}${parameter.required ? ' (required)' : ''}`).join('; ') : 'None declared'}</dd>
                <dt>Executor</dt><dd>{okf.attestedComputation.executorResource || 'Not declared'}</dd>
                <dt>Receipt</dt><dd>{okf.attestedComputation.receiptFields.join(', ') || 'Not declared'}</dd>
                <dt>Attester</dt><dd>{okf.attestedComputation.attesterResource || 'Not declared'}</dd>
              </dl>
              {#if okf.attestedComputation.contractWarnings.length}
                <p class="warning-text">{okf.attestedComputation.contractWarnings.join(' ')}</p>
              {/if}
            </section>
          {/if}
          {@const nodeLinks = smallNodeLinks(detailNode, sourceUrl)}
          {#if nodeLinks.length}
            <section class="small-node-links" aria-label="Source and resource links">
              <h3>Source and resources</h3>
              {#each nodeLinks as link}
                <a href={link.url} target="_blank" rel="noopener noreferrer">{link.label} ↗</a>
              {/each}
            </section>
          {/if}
  {/snippet}
  {#snippet data()}
          <dl>
            <dt>Route</dt><dd>{detailNode.id}</dd>
            <dt>Section</dt><dd>{detailNode.section || 'root'}</dd>
            <dt>Source</dt><dd>{metadataDisplayValue(detailNode.source)}</dd>
            <dt>Links</dt><dd>{detailRelationships.length}</dd>
          </dl>
          {@const metadataRows = smallNodeMetadataRows(detailNode)}
          {#if metadataRows.length}
            <h3>Selected metadata</h3>
            <dl>
              {#each metadataRows as row}
                <dt>{row.label}</dt><dd>{metadataDisplayValue(row.value)}</dd>
              {/each}
            </dl>
          {/if}
          <details class="json-panel">
            <summary>Node JSON and provenance</summary>
            <pre>{jsonText(detailNode)}</pre>
          </details>
  {/snippet}
</InspectorSections>
<style>
  .scope-context { background:#fff4cf; border-left:4px solid #8c7000; padding:10px; font-size:.85rem; }
  .record-relationship { border-top:1px solid #b8c7d8; padding:10px 0; display:grid; gap:6px; font-size:.85rem; }
  .record-relationship div { display:flex; flex-wrap:wrap; gap:5px; }
  .record-relationship button { min-height:36px; }
</style>
