/** Additive context contract. Source text and assertions are untrusted data. */
export type ContextBudget = {
  max_nodes: number;
  max_relationships: number;
  max_depth: number;
  max_bytes: number;
};

export type ContextProvenance = {
  url: string;
  source_sha256: string;
  locator: string;
  captured_at: string;
  source_date?: string;
  source_date_kind?: string;
  literal_sha256?: string;
};

export type ContextRecord = {
  id: string;
  route: string;
  label: string;
  kind: 'concept' | 'evidence' | 'scope';
  aliases?: Array<string | { label: string; case_sensitive: boolean }>;
  text: string;
  assertion_status: 'official' | 'normalized' | 'inferred' | 'model-derived';
  authority: { class: string; label: string; source: string };
  scope: string;
  provenance: ContextProvenance[];
  rights: string;
  access: 'public' | 'restricted';
  review_status?: string;
  conflicts_with?: string[];
};

export type ContextAssertion = {
  id: string;
  source: string;
  target: string;
  predicate: string;
  label: string;
  assertion_status: ContextRecord['assertion_status'];
  authority: ContextRecord['authority'];
  scope: string;
  provenance: ContextProvenance[];
  /** Existing bundle assertion identity, when this is a projection. */
  original_assertion_id?: string;
};

/** Author-declared evidence needs, not an answer key or an engine rule. */
export type ContextRequirement = {
  id: string;
  label: string;
  when_all: string[];
  /** Resolved concepts whose evidence needs this scoped profile covers. */
  covers?: string[];
  required: string[];
  /** Directed evidence routes which must survive assembly; never retrieval seeds. */
  required_paths?: ContextPath[];
  scope: string;
  limitations?: string[];
};

export type ContextIndex = {
  schema: 'okf-context-index.v1';
  bundle: { id: string; snapshot: string; source_url: string };
  scope: string;
  limitations: string[];
  records: ContextRecord[];
  assertions: ContextAssertion[];
  requirements: ContextRequirement[];
};

export type ContextBinding = { index_url: string; index_sha256: string };
export type BoundContextIndex = { index: ContextIndex; binding: ContextBinding };

export type ContextResolution = {
  id: string;
  label: string;
  matched: string[];
  method: 'declared-phrase';
  confidence: 'exact-alias';
};
export type ContextIssue = {
  code: string;
  message: string;
  ids: string[];
};
export type ContextPath = { seed: string; assertions: string[]; records: string[] };
export type ContextSelection = {
  record: ContextRecord;
  reasons: string[];
  paths: ContextPath[];
};
export type ContextRequirementResult = ContextRequirement & {
  status: 'supported-within-declared-scope' | 'insufficient';
  missing: string[];
};
export type ContextPackage = {
  schema: 'okf-governed-context.v1';
  context_id: string;
  engine: 'okf-context-assembly.v1';
  question: string;
  bundle: ContextIndex['bundle'];
  binding: ContextBinding;
  scope: string;
  evidence_status: 'sufficient' | 'insufficient' | 'conflicting';
  resolved_concepts: ContextResolution[];
  ambiguities: Array<{ phrase: string; candidates: string[] }>;
  unresolved_terms: string[];
  selected: ContextSelection[];
  relationships: ContextAssertion[];
  requirements: ContextRequirementResult[];
  missing_evidence: ContextIssue[];
  conflicts: ContextIssue[];
  limitations: string[];
  budget: ContextBudget & {
    used_nodes: number;
    used_relationships: number;
    used_bytes: number;
    reached_depth: number;
    truncated: boolean;
    omissions: ContextIssue[];
  };
  /** No model answer is generated by this engine. */
  ai_answer: null;
};
