import type { BundleRegistryEntry } from './types';

// A build-time projection of static/okf-registry.json keeps the landing page
// server-rendered and prevents a registry or bundle request on first load.
// learner_hub_contract.test.mjs fails if this projection drifts.
export const learningRegistry: BundleRegistryEntry[] = [
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/ai-infrastructure', title: 'AI Infrastructure', description: 'Default reference bundle generated from the AI infrastructure Markdown corpus during migration.', kind: 'local-sample', status: 'preview', version: '0.4.0', url: 'https://chris-page-gov.github.io/okf-ai-infrastructure/okf-bundle.json', home_url: 'https://chris-page-gov.github.io/okf-ai-infrastructure/' },
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/ons-data-discovery', title: 'ONS data discovery OKF', description: 'Metadata-only ONS discovery demonstrator with explicit coverage, confusable alternatives, standards evidence and MCP selection bindings.', kind: 'large-corpus', status: 'bounded-demonstrator', version: '0.2.0', url: 'https://chris-page-gov.github.io/okf-ons/okf-explorer.json', home_url: 'https://chris-page-gov.github.io/okf-ons/' },
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/gov-ckan', title: 'GOV.UK CKAN large corpus', description: 'External large-corpus exemplar using chunked CKAN metadata and static search shards.', kind: 'large-corpus', status: 'stable', version: '1.0.0', url: 'https://chris-page-gov.github.io/ai-engineering-lab-hackathon-london-2026/gov-ckan/okf-explorer.json', home_url: 'https://chris-page-gov.github.io/ai-engineering-lab-hackathon-london-2026/' },
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/uk-government-apis', title: 'UK Government APIs OKF', description: 'Multi-source API and data-access large-corpus exemplar.', kind: 'large-corpus', status: 'preview', version: '0.4.0', url: 'https://chris-page-gov.github.io/okf-uk-government-apis/okf-explorer.json', home_url: 'https://chris-page-gov.github.io/okf-uk-government-apis/' },
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/uk-legislation', title: 'UK Legislation complete work catalogue', description: 'Complete legislation.gov.uk work catalogue with live progressive CLML discovery.', kind: 'large-corpus', status: 'preview', version: '0.2.0', url: 'https://chris-page-gov.github.io/okf-uk-legislation/okf-explorer.json', home_url: 'https://chris-page-gov.github.io/okf-uk-legislation/' },
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/uk-whole-law', title: 'UK Whole-Law OKF', description: 'Federated overview of independently governed UK legal-source bundles with explicit authority, coverage, freshness and alternate access routes.', kind: 'federation', status: 'candidate', version: '0.3.0', url: 'https://chris-page-gov.github.io/okf-uk-legislation/whole-law/okf-explorer.json', home_url: 'https://chris-page-gov.github.io/okf-uk-legislation/whole-law/' },
  { id: 'https://chris-page-gov.github.io/okf-explorer/bundles/heritage-coventry-warwickshire', title: 'Coventry and Warwickshire Heritage Evaluation', description: 'Independently published Evaluation Foundry exemplar covering the faithful source-backed corpus, tiny assurance subset and isolated synthetic capability supplement; promotion evidence is carried by its signed release envelope.', kind: 'large-corpus', version: '1.0.0', url: 'https://chris-page-gov.github.io/okf-heritage-coventry-warwickshire/okf-explorer.json', home_url: 'https://chris-page-gov.github.io/okf-heritage-coventry-warwickshire/' }
];
